### ISSUE TITLE
启动出现问题

### ISSUE THREAD

**Issue by GJMZ** [WeBankFinTech/DataSphereStudio#67]
简单版
安装Linkis(0.9.2)算是正常吧，除了JDBC服务没有启动，其它服务正常启动；
简单版
安装dss(0.6.0)没有明显的错误日志，不知道怎么解决
<-------------------------------->
Begin to start dss-server
INFO: + End to start dss-server
<-------------------------------->
<-------------------------------->
Begin to start dss-flow-execution-entrance
INFO: + End to start dss-flow-execution-entrance
<-------------------------------->
<-------------------------------->
Begin to start linkis-appjoint-entrance
INFO: + End to start linkis-appjoint-entrance
<-------------------------------->
<-------------------------------->
Begin to start visualis-server
INFO: + End to start visualis-server
<-------------------------------->

**Comment by GJMZ** [comment]
主要是报错不明显，网上的资料又比较少 - -!

**Comment by pengcheng4451** [comment]
脚本有bug，我这样是没有启动成功，你需要进对应的4个组件里启动下。当然启动组件时候可能也会报错，原因是安装脚本没有把hadoop.config.dir的目录写到组件里，手动加一下就好了。
There is a bug in the script, I did not launch successfully, you need to go into the directory corresponding to the four components to launch.Of course, you might also get an error when you start a component because the installation script doesn't write the hadoop.config.dir directory to the component，just add it by hand.

**Comment by fancyChuan** [comment]
程序确实有bug，主要是通过ssh远程执行命令会造成 /etc/profile 环境变量是不生效的。而很多人JAVA_HOME是配置在/etc/profile里面的。
【解决办法】修改 bin/start-all.sh 文件
将 
`SERVER_START_CMD="source ~/.bash_profile; ....."`
改成
`SERVER_START_CMD="source /etc/profile;source ~/.bash_profile; ....."`
也就是加上 source /etc/profile;

**Comment by GJMZ** [comment]
> 程序确实有bug，主要是通过ssh远程执行命令会造成 /etc/profile 环境变量是不生效的。而很多人JAVA_HOME是配置在/etc/profile里面的。
> 【解决办法】修改 bin/start-all.sh 文件
> 将
> `SERVER_START_CMD="source ~/.bash_profile; ....."`
> 改成
> `SERVER_START_CMD="source /etc/profile;source ~/.bash_profile; ....."`
> 也就是加上 source /etc/profile;
> 
> 现在GitHub仓库代码是修复了这个问题，但是0.6.0版本就需要手动去修复了。

谢谢了，已经排查出来了，主要是你们这种调用脚本的方式报错了不会提示。
